version: '3'
services:
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    networks:
    - qgis
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - qgis-exec
  qgis-exec:
    image: qgis-exec:latest
    networks:
    - qgis
    volumes:
    - ./osm.qgs:/osm.qgs:ro
networks:
  qgis: {}

